# Generated by Django 5.1.1 on 2024-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('oldPrice', models.FloatField()),
                ('specialPrice', models.FloatField()),
                ('regularPrice', models.FloatField()),
            ],
        ),
    ]
