# Generated by Django 5.1.1 on 2024-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0002_rename_oldprice_books_oldprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.TextField(),
        ),
    ]
