# Generated by Django 5.1.1 on 2024-10-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
