# Generated by Django 5.1.1 on 2024-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0009_remove_books_favorites_favoritebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebooks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
