# Generated by Django 5.1.1 on 2024-10-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0011_alter_favoritebooks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritebooks',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RemoveConstraint(
            model_name='favoritebooks',
            name='unique_user_content_type_object_id',
        ),
        migrations.RemoveField(
            model_name='favoritebooks',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favoritebooks',
            name='object_id',
        ),
        migrations.AddField(
            model_name='favoritebooks',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newproject.books', verbose_name='Книга'),
        ),
    ]
