# Generated by Django 5.1.1 on 2024-10-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0013_remove_cart_book_remove_cart_session_key_cart_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newproject.books', verbose_name='Книга'),
        ),
    ]
