# Generated by Django 5.1.1 on 2024-10-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0014_cart_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='book',
            new_name='book_id',
        ),
    ]
