# Generated by Django 5.1.1 on 2024-10-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0015_rename_book_cart_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
